packaging_format = 2

id = "zulip"
name = "Zulip"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "1.0~ynh1"

maintainers = ["johndoe"]

[upstream]
license = "free"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://zulip.readthedocs.io/"
userdoc = "https://yunohost.org/apps"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://download.zulip.com/server/zulip-server-latest.tar.gz"
        sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "deb1, deb2, php8.0-foo, php8.0-bar"

    [resources.database]
    type = "mysql"
